app = 'quetzal'
primary_region = 'waw'

[build]

[http_service]
  internal_port = 3002
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
